// file: lib/firebase_options.dart
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Using a clearer name: 'web'
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // ADDED: return the Android options
      case TargetPlatform.iOS:
        return ios; // ADDED: return the iOS options
      case TargetPlatform.macOS:
        return macos; // ADDED: return the macOS options
      case TargetPlatform.windows:
        return windows; // ADDED: return the Windows options
      case TargetPlatform.linux:
        return linux; // ADDED: return the Linux options
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // NOTE: Replace the values for Android, iOS, etc., with the specific
  // values generated by the FlutterFire CLI or copied from the Firebase Console.

  // --- Web Configuration (already present) ---
  static const web = FirebaseOptions(
    apiKey: 'AIzaSyBr9trhfOFh63D6GWy4W3-gcXudjhFQDRw',
    appId: '1:157745700174:web:c4e32c93148cd566b3121f',
    messagingSenderId: '157745700174',
    projectId: 'bakeryapp01',
    authDomain: 'bakeryapp01.firebaseapp.com',
    storageBucket: 'bakeryapp01.firebasestorage.app',
    measurementId: 'G-8SN8HMJZB0',
  );

  // --- Android Configuration (Missing) ---
  static const android = FirebaseOptions(
    // You MUST provide the correct values here
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId:
        'YOUR_ANDROID_APP_ID', // e.g., 1:157745700174:android:xxxxxxxxxxxxxxxx
    messagingSenderId: '157745700174',
    projectId: 'bakeryapp01',
    storageBucket: 'bakeryapp01.firebasestorage.app',
  );

  // --- iOS Configuration (Missing) ---
  static const ios = FirebaseOptions(
    // You MUST provide the correct values here
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID', // e.g., 1:157745700174:ios:xxxxxxxxxxxxxxxx
    messagingSenderId: '157745700174',
    projectId: 'bakeryapp01',
    storageBucket: 'bakeryapp01.firebasestorage.app',
    // iOS and macOS typically require a 'clientId' and 'databaseURL' as well
    // clientId: 'YOUR_IOS_CLIENT_ID',
    // databaseURL: 'https://bakeryapp01.firebaseio.com',
  );

  // --- macOS Configuration (Missing) ---
  static const macos = FirebaseOptions(
    // You MUST provide the correct values here
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID', // e.g., 1:157745700174:macos:xxxxxxxxxxxxxxxx
    messagingSenderId: '157745700174',
    projectId: 'bakeryapp01',
    storageBucket: 'bakeryapp01.firebasestorage.app',
    // clientId: 'YOUR_MACOS_CLIENT_ID',
  );

  // --- Windows Configuration (Missing) ---
  static const windows = FirebaseOptions(
    // You MUST provide the correct values here
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: '157745700174',
    projectId: 'bakeryapp01',
    storageBucket: 'bakeryapp01.firebasestorage.app',
  );

  // --- Linux Configuration (Missing) ---
  static const linux = FirebaseOptions(
    // You MUST provide the correct values here
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: '157745700174',
    projectId: 'bakeryapp01',
    storageBucket: 'bakeryapp01.firebasestorage.app',
  );
}
